$ANSIBLE_VAULT;1.1;AES256
30623262316466663164343861363966366139313863666539336461343432633734656231656438
3538663431353332366365343637623863396437313633350a663132636331343531653261313533
61303433373737326166336263303233653865303639643038326265396633666465643734343033
6562653861313639350a396566666562616232376632366537643731653730386330623664623435
66353861373131636162643637626466323464376239383838323862353333323136353234393663
30303364386432343435323763303035343633663433663637386465356135323862653431323134
30646364386361646137656537343165396361366165623430613833353730373338326666323339
32623764346137333733366538346466353164313061333464663835383731653733646635663566
3836
